
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {
    private SmartCardWord smartCardWord;
    private CardLayout cardLayout;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        setSize(800, 600);
        setTitle("Java Card OS");
        
        initComponents();
        
        setResizable(false);
        smartCardWord = new SmartCardWord();
        cardLayout = (CardLayout) parentPanel.getLayout();
        
        setBackgroundColor();
        enableFunction(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        entryPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        pinButton = new javax.swing.JButton();
        openChangePinButtion = new javax.swing.JButton();
        openAdminPanel = new javax.swing.JButton();
        createPinPanel = new javax.swing.JPanel();
        back1Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pinTextField = new javax.swing.JTextField();
        pinConfirmTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createPinButton = new javax.swing.JButton();
        changePinPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newPinTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newPinConfirmTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        oldPinTextField = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        adminPanel = new javax.swing.JPanel();
        backButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        parentPanel.setLayout(new java.awt.CardLayout());

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectCard(evt);
            }
        });

        pinButton.setText("Tạo PIN");
        pinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCreatePinPanel(evt);
            }
        });

        openChangePinButtion.setText("Đổi PIN");
        openChangePinButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openChangePinPanel(evt);
            }
        });

        openAdminPanel.setText("Admin");
        openAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminFunction(evt);
            }
        });

        javax.swing.GroupLayout entryPanelLayout = new javax.swing.GroupLayout(entryPanel);
        entryPanel.setLayout(entryPanelLayout);
        entryPanelLayout.setHorizontalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openChangePinButtion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addComponent(openAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        entryPanelLayout.setVerticalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(pinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(openChangePinButtion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        parentPanel.add(entryPanel, "card2");

        createPinPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        back1Button.setText("Back");
        back1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToEntry(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KHỞI TẠO PIN CHO THẺ");

        jLabel2.setText("Nhập PIN:");

        jLabel3.setText("Nhập lại PIN:");

        createPinButton.setText("Xác nhận");
        createPinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPin(evt);
            }
        });

        javax.swing.GroupLayout createPinPanelLayout = new javax.swing.GroupLayout(createPinPanel);
        createPinPanel.setLayout(createPinPanelLayout);
        createPinPanelLayout.setHorizontalGroup(
            createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPinPanelLayout.createSequentialGroup()
                .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createPinPanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(createPinPanelLayout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jLabel1))
                                .addGroup(createPinPanelLayout.createSequentialGroup()
                                    .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pinConfirmTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pinTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(createPinPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(createPinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        createPinPanelLayout.setVerticalGroup(
            createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPinPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(112, 112, 112)
                .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(createPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(createPinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(back1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parentPanel.add(createPinPanel, "card3");

        changePinPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ĐỔI PIN CHO THẺ");

        jLabel5.setText("Nhập PIN:");

        jLabel6.setText("Nhập lại PIN:");

        jLabel7.setText("Nhập PIN cũ:");

        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToEntry(evt);
            }
        });

        confirmButton.setText("Xác nhận");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangePin(evt);
            }
        });

        javax.swing.GroupLayout changePinPanelLayout = new javax.swing.GroupLayout(changePinPanel);
        changePinPanel.setLayout(changePinPanelLayout);
        changePinPanelLayout.setHorizontalGroup(
            changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePinPanelLayout.createSequentialGroup()
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changePinPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(changePinPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(oldPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(changePinPanelLayout.createSequentialGroup()
                                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newPinConfirmTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newPinTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePinPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePinPanelLayout.createSequentialGroup()
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePinPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(307, 307, 307))))
        );
        changePinPanelLayout.setVerticalGroup(
            changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePinPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(58, 58, 58)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPinConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parentPanel.add(changePinPanel, "card4");

        backButton2.setText("Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToEntry(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(686, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parentPanel.add(adminPanel, "card5");

        getContentPane().add(parentPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectCard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectCard
        // TODO add your handling code here:
        connectCard();
    }//GEN-LAST:event_connectCard

    private void openCreatePinPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCreatePinPanel
        pinTextField.setText(null);
        pinConfirmTextField.setText(null);
        cardLayout.show(parentPanel, "card3");
    }//GEN-LAST:event_openCreatePinPanel

    private void backToEntry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToEntry
        cardLayout.show(parentPanel, "card2");
    }//GEN-LAST:event_backToEntry

    private void createPin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPin
        String pin = pinTextField.getText();
        String pinConfirm = pinConfirmTextField.getText();
        if (pin.length() != 4) {
            JOptionPane.showMessageDialog(parentPanel, "Mã PIN cần có độ dài là 4");
            return;
        }
        if (!pinConfirm.equals(pin)) {
            JOptionPane.showMessageDialog(parentPanel, "Mã PIN không giống, kiểm tra lại");
            return;
        }
        if (!pin.matches("\\d+")) {
            JOptionPane.showMessageDialog(parentPanel, "Mã PIN chỉ chứa số 0-9");
            return;
        }
        smartCardWord.createPin(pin);
    }//GEN-LAST:event_createPin

    private void confirmChangePin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangePin
        // TODO add your handling code here:
        String pin = oldPinTextField.getText();
        if (smartCardWord.checkPin(pin)) {
            String newPin = newPinTextField.getText();
            String confirmNewPin = newPinConfirmTextField.getText();
            if (newPin.length() != 4) {
                JOptionPane.showMessageDialog(parentPanel, "Mã PIN cần có độ dài là 4");
                return;
            }
            if (!confirmNewPin.equals(newPin)) {
                JOptionPane.showMessageDialog(parentPanel, "Mã PIN không giống, kiểm tra lại");
                return;
            }
            if (!newPin.matches("\\d+")) {
                JOptionPane.showMessageDialog(parentPanel, "Mã PIN chỉ chứa số 0-9");
                return;
            }
            smartCardWord.changePin(newPin);
        }
    }//GEN-LAST:event_confirmChangePin

    private void openChangePinPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openChangePinPanel
        // TODO add your handling code here:
        oldPinTextField.setText(null);
        newPinTextField.setText(null);
        newPinConfirmTextField.setText(null);
        cardLayout.show(parentPanel, "card4");
    }//GEN-LAST:event_openChangePinPanel

    private void adminFunction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFunction
        // TODO add your handling code here:
        cardLayout.show(parentPanel, "card5");
    }//GEN-LAST:event_adminFunction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton back1Button;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JPanel changePinPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createPinButton;
    private javax.swing.JPanel createPinPanel;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField newPinConfirmTextField;
    private javax.swing.JTextField newPinTextField;
    private javax.swing.JTextField oldPinTextField;
    private javax.swing.JButton openAdminPanel;
    private javax.swing.JButton openChangePinButtion;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton pinButton;
    private javax.swing.JTextField pinConfirmTextField;
    private javax.swing.JTextField pinTextField;
    // End of variables declaration//GEN-END:variables

    private void connectCard() {
        if (smartCardWord.isConnected()) {
            connectButton.setText("Connect");
            smartCardWord.disconnect();
            JOptionPane.showMessageDialog(rootPane, "Ngắt kết nối thành công");
            enableFunction(false);
            entryPanel.setBackground(Color.red);
        } else {
            boolean check = smartCardWord.connectAndSelectDefaultApplet();
            if (check) {
                connectButton.setText("Disconnect");
                JOptionPane.showMessageDialog(rootPane, "Kết nối thành công");
                enableFunction(true);
                entryPanel.setBackground(Color.GREEN);
            }
        }
    }
    
    private void enableFunction(boolean enable) {
        pinButton.setEnabled(enable);
        openChangePinButtion.setEnabled(enable);
    }

    private void setBackgroundColor() {
        entryPanel.setOpaque(true);
        entryPanel.setBackground(Color.red);
    }
    
}
